# Configuration for the Reservoir module
reservoir:
  n_inputs: 4
  n_outputs: 2
  n_reservoir: 100
  spectral_radius: 0.9
  sparsity: 0.1
  noise: 0.001
  random_state: 42
  leaking_rate: 1.0
  input_scaling: 1.0
  num_layers: 1
  type: "rnn" # Type of reservoir: "rnn", "snn", etc.
